version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=app
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./data/db:/data/db
  
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_URL=mongodb://mongoadmin:secret@mongo:27017
    depends_on:
      - mongo
